services:
  f1-api:
    build:
      context: .
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    ports:
      - "1212:8000"
    volumes:
      - ./cache:/app/cache
      - ./output:/app/output
    environment:
      - FASTF1_CACHE_DIR=/app/cache
