services:
  - type: web
    name: f1-telemetry-api
    env: python
    buildCommand: pip install -r requirement.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CACHE_TTL_MINUTES
        value: "30"
      - key: MAX_DRIVERS
        value: "6"
      - key: ALLOWED_ORIGIN
        value: "*"